name: release-dev-a
on:
  push:
    branches:
      - devA
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.30.0
        if: |
          github.repository_owner == 'ptarmiganlabs'
        with:
          # token: ${{ secrets.PAT }}
          release-type: simple
          package-name: lab-pr-devA
          default-branch: devA
 